version: '3.3'

services:
    typescript:
        tty: true
        image: node:16.13.0
        env_file:
            - .env
        volumes:
            - ./:/home/node
        working_dir: /home/node
        expose:
            - "${API_PORT}"
        ports:
            - "${API_PORT}:${API_PORT}"
        depends_on:
            - database
        links:
            - database
        command: bash -c "npm i && npm run serve"
        restart: "always"
        networks:
          - api-template-networks

    database:
        image: "postgres:13"
        expose:
          - "${POSTGRES_PORT}"
        ports:
          - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        environment:
          TZ: ${API_TZ}
          LC_ALL: C.UTF-8
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        volumes:
          - db-data:/var/lib/postgresql/data
          - ./sql/crypt.sql:/docker-entrypoint-initdb.d/crypt.sql
        env_file:
          - .env
        command: -p ${POSTGRES_PORT}
        restart: "always"
        networks:
          - api-template-networks

volumes:
    db-data:

networks:
    api-template-networks: